name: GitHub Pages
on:
  push:
    branches:
      - dev
      - dev-update
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: write
  issues: read
  discussions: read
  packages: read
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04 # ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout dennykorsukewitz.github.io
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
        with:
          path: pages
          submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Add dennykorsukewitz (GitHub Profile)
        run: pages/.github/workflows/pages/github-profile.sh

      - name: Add Repository List
        run: pages/.github/workflows/pages/repositories.sh

      - name: Create release blog posts
        run: pages/.github/workflows/pages/posts.sh

      - name: Add Monitoring
        run: pages/.github/workflows/pages/monitoring.sh

      - name: Add Repository Tab
        run: pages/.github/workflows/pages/repositories_tab.sh

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: pages
          ruby-version: 3
          bundler-cache: true

      - name: Build site
        run: cd "${GITHUB_WORKSPACE}/pages" && bundle exec jekyll build --source "${GITHUB_WORKSPACE}/pages/" --destination "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      # - name: Test site
      #   run: |
      #     cd "${GITHUB_WORKSPACE}/pages" && bundle exec htmlproofer _site \
            # \-\-disable-external=true \
            # \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "pages/_site${{ steps.pages.outputs.base_path }}"

  Deploy:
    environment:
      name: GitHub-Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  Screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Checkout dennykorsukewitz.github.io
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
        with:
          path: pages

      - name: Install capture-website-cli
        run: npm install --global capture-website-cli

      #- name: Install chrome
      #  uses: browser-actions/setup-chrome@v1

      - name: Screenshots
        run: pages/.github/workflows/pages/screenshots.sh

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated Screenshots.'