name: GitHub Pages
on:
  push:
    branches:
      - dev
      - dev-update
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04 # ubuntu-latest
    env:
      REPOSITORIES: 'DK4 DK4Znuny-VisualStudioCode DK4Znuny-QuickDelete DK4OTRS-UBInventory MRBS-OTRS'
    steps:
      - name: Checkout dennykorsukewitz.github.io
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          path: pages
          submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Add dennykorsukewitz (GitHub Profile)
        run: pages/.github/workflows/pages/github-profile.sh

      - name: Add Repository List
        run: pages/.github/workflows/pages/repository.sh

      - name: Create release blog posts
        run: pages/.github/workflows/pages/posts.sh

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: pages
          ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true

      - name: Build site
        run: cd "${GITHUB_WORKSPACE}/pages" && bundle exec jekyll build --source "${GITHUB_WORKSPACE}/pages/" --destination "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      # - name: Test site
      #   run: |
      #     cd "${GITHUB_WORKSPACE}/pages" && bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "pages/_site${{ steps.pages.outputs.base_path }}"

  Deploy:
    environment:
      name: GitHub-Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
